title: 프로그래머 이규원의 웹사이트
author: 이규원
email: gyuwon@live.com
github_username: gyuwon
facebook_username: gyuwon.yi
linkedin_username: gyuwonyi

show_excerpts: true
excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-135516945-1
